// Site-wide constants used for canonical URLs, OG tags, and JSON-LD.

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? 'https://news.luuhailong.com'
).replace(/\/$/, '');

export const SITE_NAME = 'Lưu Hải Long — Personal Blog';
export const SITE_TAGLINE = 'AI, Công Nghệ & Lập Trình';
export const SITE_DESCRIPTION =
  'Chia sẻ kiến thức chuyên sâu về AI, công nghệ và lập trình. Bài viết phân tích, hướng dẫn và đánh giá công cụ mới nhất. Bởi Lưu Hải Long.';
export const AUTHOR_NAME = 'Lưu Hải Long';
export const TWITTER_HANDLE = '@hailongluu';
export const LOCALE = 'vi_VN';

// Hosts the backend may bake into absolute media URLs (APP_BASE_URL / internal
// service name) that must never leak into public meta — rewrite them to SITE_URL.
const INTERNAL_HOSTS = new Set(['localhost', '127.0.0.1', 'blog-api', 'public-web']);

/** Absolute, public URL for a site-relative path or a backend media URL. */
export function absUrl(path = '/'): string {
  if (/^https?:\/\//.test(path)) {
    try {
      const u = new URL(path);
      if (INTERNAL_HOSTS.has(u.hostname)) return SITE_URL + u.pathname + u.search;
      return path;
    } catch {
      return path;
    }
  }
  return SITE_URL + (path.startsWith('/') ? path : `/${path}`);
}

/** Dynamic OG image URL (PNG) generated by the /og route. */
export function ogImageUrl(opts: { title?: string; subtitle?: string; author?: string }): string {
  const params = new URLSearchParams();
  if (opts.title) params.set('title', opts.title);
  if (opts.subtitle) params.set('subtitle', opts.subtitle);
  if (opts.author) params.set('author', opts.author);
  const qs = params.toString();
  return absUrl(`/og${qs ? `?${qs}` : ''}`);
}
