spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: WARN
    com.blog.cms: INFO
blog:
  cookie:
    secure: true
server:
  error:
    include-message: never
    include-binding-errors: never
